/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import Clases.*;

/**
 *
 * @author esteacosta
 */
public class Anadir_linea extends javax.swing.JFrame {
Grafo lineas_metro;
AnadirLinea_Error error;
AnadirLinea_Info info;
String nombre_linea;
Lista line;
Interfaz1 interfaz;
    /**
     * Creates new form Anadir_linea
     */
    public Anadir_linea(Grafo lineas_metro, Interfaz1 interfaz) {
        initComponents();
        this.lineas_metro = lineas_metro;  
        this.info = new AnadirLinea_Info();
        this.error = new AnadirLinea_Error();
        nombre_linea = null;
        this.Anadir.setVisible(false);
        this.interfaz = interfaz;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAnadir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Terminado = new javax.swing.JButton();
        Informacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NombreLinea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoParada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoConexion = new javax.swing.JTextArea();
        Anadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelAnadir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LabelAnadir.setText("Añadir Línea");

        jLabel1.setText("La línea debe llevar al menos una conexión con una parada existente");

        jLabel2.setText("Parada");

        jLabel3.setText("Conexión");

        Terminado.setBackground(new java.awt.Color(204, 255, 204));
        Terminado.setText("Terminar");
        Terminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminadoActionPerformed(evt);
            }
        });

        Informacion.setBackground(new java.awt.Color(153, 204, 255));
        Informacion.setText("Información");
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingresa el nombre de la Linea");

        NombreLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreLineaActionPerformed(evt);
            }
        });

        infoParada.setColumns(20);
        infoParada.setRows(5);
        jScrollPane1.setViewportView(infoParada);

        infoConexion.setColumns(20);
        infoConexion.setRows(5);
        jScrollPane2.setViewportView(infoConexion);

        Anadir.setText("Añadir Parada");
        Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAnadir)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(NombreLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Informacion)
                                        .addGap(46, 46, 46)
                                        .addComponent(Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Terminado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LabelAnadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(NombreLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Terminado)
                    .addComponent(Informacion)
                    .addComponent(Anadir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        // TODO add your handling code here:
        info.setVisible(true);
    }//GEN-LAST:event_InformacionActionPerformed

    private void TerminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminadoActionPerformed
      // TODO add your handling code here:
        if (line != null){
            Nodo2 nLinea = new Nodo2(this.line.Primero());
            this.lineas_metro.agregar(nLinea);
            interfaz.actualizarConexiones(lineas_metro);
        } else {
            this.error.Error(2);
        }
        this.setVisible(false);
    }//GEN-LAST:event_TerminadoActionPerformed

    private void NombreLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreLineaActionPerformed
        // TODO add your handling code here:
        this.nombre_linea = this.NombreLinea.getText();
        if (nombre_linea == null && nombre_linea.trim().isEmpty()){
            this.error.Error(1);
            this.nombre_linea = null;
        } else {
            this.Anadir.setVisible(true);
        }
    }//GEN-LAST:event_NombreLineaActionPerformed

    private Nodo Buscar_Parada(String nombre){
        Nodo2 aux;
        Nodo pAux;
        boolean encontrado = false;
        aux = lineas_metro.primero();
        pAux = aux.getData();
        while (aux != null & !encontrado){
            while (pAux != null & !encontrado){
                if (pAux.Parada().Nombre().trim().equals(nombre)){
                    encontrado = true;
                } 
                pAux = pAux.getpNext();
            }
            aux = aux.getpNext();
            pAux = aux.getData();
        }
        return pAux;
    }
    
    private void AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirActionPerformed
        // TODO add your handling code here:
        line = new Lista(nombre_linea);
        String parada = this.infoParada.getText().trim();
        String conection = this.infoConexion.getText().trim();
        if (parada != null & !parada.trim().isEmpty()){
            if (conection == null & parada.trim().isEmpty()){
                Parada p = new Parada(parada, nombre_linea);
                Nodo Nparada = new Nodo(p);
                this.line.agregar(Nparada);
            } else {
                Nodo connect = this.Buscar_Parada(conection);
                if (connect != null){
                    if (connect.getpLNext() != null){
                        Parada p = new Parada(parada, nombre_linea);
                        Nodo Nparada = new Nodo(p);
                        connect.setpLNext(Nparada);
                        Nparada.setpLPrev(connect);
                        this.line.agregar(Nparada);
                    } else {
                        if (connect.getpLNext().Parada().Nombre().trim().equals(parada)){
                            Nodo Nparada = connect.getpLNext();
                            this.line.agregar(Nparada);
                        } else {
                            this.error.Error(4);
                        }
                    }
                } else {
                    this.error.Error(3);
                }
            }
        } else {
            this.error.Error(1);
        }
        this.infoParada.setText(null);
        this.infoConexion.setText(null);
    }//GEN-LAST:event_AnadirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anadir;
    private javax.swing.JButton Informacion;
    private javax.swing.JLabel LabelAnadir;
    private javax.swing.JTextField NombreLinea;
    private javax.swing.JButton Terminado;
    private javax.swing.JTextArea infoConexion;
    private javax.swing.JTextArea infoParada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
