/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import Clases.Grafo;

/**
 *
 * @author maria
 */
public class InterfazCobertura extends javax.swing.JFrame {

    Grafo lineas_metro;

    /**
     * Creates new form InterfazCobertura
     */
    public InterfazCobertura(Grafo lineas_metro) {
        initComponents();
        this.lineas_metro = lineas_metro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BuscarProfundidad = new javax.swing.JButton();
        completaProfundidad = new javax.swing.JButton();
        sucursalUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        BuscarAmplitud = new javax.swing.JButton();
        completaAmplitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Selecciona el metodo de busqueda");

        BuscarProfundidad.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        BuscarProfundidad.setText("Cobertura de Sucursles por Profundidad");
        BuscarProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProfundidadActionPerformed(evt);
            }
        });

        completaProfundidad.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        completaProfundidad.setText("Cobertura Completa por Profundidad");
        completaProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completaProfundidadActionPerformed(evt);
            }
        });

        sucursalUsuario.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        sucursalUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Ingresa la surcursal de Partida");

        Resultado.setColumns(20);
        Resultado.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("Resultado");

        BuscarAmplitud.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        BuscarAmplitud.setText("Cobertura de Sucursales por Amplitud");
        BuscarAmplitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAmplitudActionPerformed(evt);
            }
        });

        completaAmplitud.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        completaAmplitud.setText("Cobertura Completa por Amplitud");
        completaAmplitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completaAmplitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarProfundidad)
                            .addComponent(completaProfundidad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(completaAmplitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BuscarAmplitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sucursalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addGap(0, 200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sucursalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(BuscarProfundidad)
                        .addGap(18, 18, 18)
                        .addComponent(completaProfundidad)
                        .addGap(48, 48, 48)
                        .addComponent(BuscarAmplitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completaAmplitud)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProfundidadActionPerformed
        // TODO add your handling code here:
        String resultado = this.lineas_metro.CoberturaSucursalProfundidad(this.sucursalUsuario.getText());
        this.Resultado.setText(resultado);
    }//GEN-LAST:event_BuscarProfundidadActionPerformed

    private void completaProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completaProfundidadActionPerformed
        // TODO add your handling code here:
        String resultado = this.lineas_metro.ComprobarCoberturaCompletaProfundidad();
        if (resultado.equals("")) {
            this.Resultado.setText("Hay Cobertura Completa");
        } else {
            this.Resultado.setText("No hay cobertura completa, faltan las paradas:" + resultado);
        }
    }//GEN-LAST:event_completaProfundidadActionPerformed

    private void sucursalUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucursalUsuarioActionPerformed

    private void BuscarAmplitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAmplitudActionPerformed
        // TODO add your handling code here:
        String resultado = this.lineas_metro.CoberturaSucursalAmplitud(this.sucursalUsuario.getText());
        this.Resultado.setText(resultado);
    }//GEN-LAST:event_BuscarAmplitudActionPerformed

    private void completaAmplitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completaAmplitudActionPerformed
        // TODO add your handling code here:
        String resultado = this.lineas_metro.ComprobarCoberturaCompletaAmplitud();
        if (resultado.equals("")) {
            this.Resultado.setText("Hay Cobertura Completa");
        } else {
            this.Resultado.setText("No hay cobertura completa, faltan las paradas:" + resultado);
        }
    }//GEN-LAST:event_completaAmplitudActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarAmplitud;
    private javax.swing.JButton BuscarProfundidad;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton completaAmplitud;
    private javax.swing.JButton completaProfundidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sucursalUsuario;
    // End of variables declaration//GEN-END:variables
}
